name: newsapp
description: A Flutter app for displaying news with bottom navigation and API support.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.6
  webview_flutter: ^4.7.0  # Untuk tampilan berita asli di aplikasi (WebView)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/        # Folder gambar (pastikan folder ini ada meskipun kosong)
